### ISSUE TITLE
Ideas - todo

### ISSUE THREAD

**Issue by mrkvon** [ditup/ditapi#43]
- [x] create idea
- [ ] read idea by id
- idea tags
  - [ ] add
  - [ ] remove
- list ideas
  - [ ] with tags
  - [ ] created by somebody
  - [ ] commented by somebody
  - [ ] with my tags
  - [ ] new
  - [ ] random
  - [ ] highly rated
  - [ ] trending
  - [ ] related to other ideas by tags
- [ ] search ideas by title
- [ ] owner (creator) can edit an idea
- [ ] delete
- [ ] vote
- comments and reactions to comments
  - [ ] create comment, reaction
  - [ ] delete comment, reaction
  - [ ] vote comment, reaction
- [ ] watch idea
- ...

Figure out:
- how to collaboratively work on ideas
- how to group similar or duplicate ideas
- how to reference ideas between each other
- what about tag popularity etc.
