### ISSUE TITLE
Challenges - todo

### ISSUE THREAD

**Issue by agatatalita** [ditup/ditapi#63]
- [x] write general tests for ideas and challenges
- [x] write a general model for ideas and challenges 
- [ ] generalize validation or not
- [x] generalize controllers or not
- [ ] generalize serializers or not
- [ ] goto for challenges

THE SAME AS IN IDEAS:
- [x] create a challenge
- [x] read challenge by id
- [x] update challenge
- challenge tags
  - [x] add
  - [x] read
  - [x] remove
- list challenges
  - [x] with tags
  - [x] created by somebody
  - [x] commented by somebody
  - [x] with my tags
  - [x] new
  - [x] random
  - [x] highly rated
  - [x] trending
  - ~~related to other challenges by tags~~ (do later)
- [x] search challenges by title (only if feasible)
- [x] owner (creator) can edit a challenge
- ~~delete~~ (needs more thinking)
- [x] vote
- comments and reactions to comments
  - [x] create comment
  - [x] read comments of the challenge
  - [x] update comment
  - [x] delete comment
  - [x] vote comment
  - [x] CRUD reaction
  - ~~vote reactions~~ (someday, maybe)
- [ ] watch challenge
  - [ ] watch, unwatch
  - [ ] count watches
  - [ ] see users who watch
  - [ ] see what ideas a set of users watch
  - [ ] notify users who watch.
  - What is the difference between watching, subscribing (wanting to be notified), and expressing interest in the challenge (as in "I care about this")? Is it the same?
- make challenges (in limited form) visible to non-logged users.

It is so far the common 'figure out' with #43  
- [ ] Probably needs a separate issue?

Figure out:
- how to collaboratively work on challenges
- how to group similar or duplicate challenges
- how to reference challenges between each other
- what about tag popularity etc.
- challenge creator: reference or edge?
